# Makefile for my renderer library PaCaLib
# This is the Android implementation
#

NAME                 =  PaCaLib_Android
VERS_MAJOR           =  0
VERS_MINOR           =  1

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

export SRCDIR        =  .

include $(SCRIPTDIR)/makelib

